- name: intsall nginx
  hosts: local
  connection: local # for connecting same server
  become: yes # get sudo or root access
  tasks:
  - name: intsall
    ansible.builtin.package: # module used for install package
      name: nginx
      state: present # present means installed, absent means uninstall
  - name: Start service nginx, if not started
    ansible.builtin.service: # module for start the service 
      name: nginx
      state: started
      enabled: yes # service will up automatically when server reboot