- name: ping the server 
  hosts: local
  connection: local
  tasks:
  - name: ping the server
    ansible.builtin.ping:
    register: output_value
  - name: print the output
    ansible.builtin.debug:
      msg: "{{ output_value }}"

