- name: delcarion of variables
  hosts: local
  connection: local
  vars: #variable declaration at play level
    course: "aws with DevOps"
  tasks:
  - name: variable declartion
    ansible.builtin.debug:
      msg: "I am learning {{ course }}"
      