- name: declare variable 
  hosts: local
  connection: local
  tasks:
  - name: variable decalre at task level
    vars: # variable declare at task level
      course: "AWS with DevOps"
    ansible.builtin.debug:
      msg: "I am learning {{ course }}"

