- name: variable declare in prompt 
  hosts: local
  connection: local
  vars_prompt:
    - name: course
      prompt: "Enter course name"
      Private: false # To display the entered value. defualt it hidden
  tasks:
  - name: prompt level declaration
    ansible.builtin.debug:
      msg: "I am learning {{ course }}"