- name: install multiple packages
  hosts: local
  connection: local
  become: yes
  vars: #method1 declare list of variables 
    list_of_packages:
      - nginx 
      - mysql
      - httpd

  tasks:
  - name: install packages 
    ansible.builtin.package:
      #name: "{{ item }}"
      name: "{{ list_of_packages }}"
      state: present
    # loop:
    # - nginx
    # - mysql
    # - httpd
    loop: "{{ list_of_packages }}"