- name: install and remove packages
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: pcakages install and uninstall
    ansible.builtin.package:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop:
    - { name: 'mysql',state: 'absent'}
    - { name: 'nginx',state: 'present'}
    - { name: 'httpd',state: 'absent'}
     