- name: demo on filters/functions
  hosts: local
  connection: local
  tasks:
  # declare the defulat value to variable
  - name: print the defualt variable
    ansible.builtin.debug:
      msg: "Hello, welcome to {{ Course | defualt ('Ansible') }}"
  #convert to upper case
  - name: conver to upper
    vars: 
      grettings: "Hello uday"
    ansible.builtin.debug:
      msg: "{{ grettings | upper }}"
  #convert to lowe case    
  - name: conver to lower
    vars: 
      grettings: "HELLO UDAY"
    ansible.builtin.debug:
      msg: "{{ grettings | upper }}"
  # get unique values from List 
  - name: get unique vales
    vars:
      numbers: [1,2,2,4,3,4,5,5]
    ansible.builtin.debug:
      msg: "{{ numbers | unique }}"
  # get t=min and max value 
  - name: get the min and max
    vars:
      numbers: [1,2,4,5,7,45,80]
    ansible.builtin.debug:
      msg: "min value: {{ numbers | min }}, Max value: {{ numbers | max }}"
  # convert map to list
  - name: convert map to list
    vars:
      course:
        name: "Devops with AWS" 
        Duration: 120
    ansible.builtin.debug:
      msg: "{{ course | dict2items }}"