- name: create ec2 instance
  hosts: local
  connection: local
  vars:
    zone: devopskiran.online

    instanaces:
    - mysql
    - backend
    - frontend

  tasks: 
  - name: install boto3 and botocore
    ansible.builtin.pip:
      name: 
      - boto3
      - botocore
      executable: pip3.9
  - name: craete ec2 instance
    #name- ami id 
    #region
    #keypair
    #security group
    #instance type
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      instance_type: t2.micro
      image_id: ami-09c813fb71547fc4f
      region: us-east-1
      security_group: sg-0e636a545591b4349
      vpc_subnet_id: subnet-08ecc8029a7be6e48 # need to take sub_net id 
    loop: "{{ instanaces }}"
    register: ec2_info
  - name: print the ec2 information
    ansible.builtin.debug:
      msg: "{{ ec2_info }}"
  
    
# create route 53
  - name : create route53 with private ip address
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{ item.item }}.{{ zone }}"
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
      wait: true
    loop: "{{ ec2_info.results }}"

  
