- name: create ec2 instance
  hosts: local
  connection: local
  tasks: 
  - name: install boto3 and botocore
    ansible.builtin.pip:
      name: 
      - boto3
      - botocore
      executable: pip3.9
  - name: craete ec2 instance
    #name- ami id 
    #region
    #keypair
    #security group
    #instance type
    amazon.aws.ec2_instance:
      name: "ansible"
      instance_type: t2.micro
      image_id: ami-09c813fb71547fc4f
      region: us-east-1
      security_group: sg-0e636a545591b4349
      vpc_subnet_id: vpc-037525ac174643f78 
  
